### ISSUE TITLE
Allow logfile for possible future debugging and/or checking?

### ISSUE THREAD

**Issue by varenius** [jive-vlbi/etransfer#10]
By default, etd is deamonised with no output. etc displays output on screen, depending on the message level set. I think it could be useful to have the option to specify a logfile (or perhaps better, a log directory) when starting both etd and etc. Sometimes things break (for unknown reasons) and then it would be useful to have the log already, rather than having to e.g. run etd in foreground and then grab the output. In particular useful for tracking down things which may happen outside office hours?

The logfile could have a different (more verbose) level than the default command line output, and possibly use the message level specified to the etd/etc call if non-default.

**Comment by haavee** [comment]
Check `/var/log/*` - when daemonized `etd` writes to the systemlog (because that's what deamons should do, right?), and uses:
- https://linux.die.net/man/3/openlog with parameters **("etd", `LOG_PID`, `LOG_USER`)**
- https://man7.org/linux/man-pages/man3/syslog.3.html to log messages with parameters 
  **(_current debug level_, "%s", `actual debug msg`)**

**Comment by varenius** [comment]
Hm. I ran etd deamonized, but I cannot find any etd lines in /var/log/*. I guess "grep etd /var/log/*" should show something, but it doesn't. This is an issue on linux, so my first guess would be permissions. But I guess I should not need to run etd as root or something for it to have access to syslog? Hm. Do you get log entries in other places?

**Comment by haavee** [comment]
**[flexbuf4 (socket-options)]Okay->date**
Fri May 21 15:48:57 CEST 2021

**[flexbuf4 (socket-options)]Okay->./Linux-x86_64-native-opt/etd --command tcp:// --data udt:// -m 4**

**[flexbuf4 (socket-options)]Okay->sudo grep etd /var/log/syslog**
May 21 15:49:04 flexbuf4 ./Linux-x86_64-native-opt/etd[949]: 2021-05-21 13:49:04.20: sigwaiterthread: enter wait phase
May 21 15:49:04 flexbuf4 ./Linux-x86_64-native-opt/etd[949]: 2021-05-21 13:49:04.20: etd: server is-at <udt/0.0.0.0:8008/mss=1500,max-bw=-1>
May 21 15:49:04 flexbuf4 ./Linux-x86_64-native-opt/etd[949]: 2021-05-21 13:49:04.20: server/UDT rcvbuf = 33554240 sndbuf = 335543872 linger=0:0 mss=1500 max_bw=Inf
May 21 15:49:04 flexbuf4 ./Linux-x86_64-native-opt/etd[949]: 2021-05-21 13:49:04.20: etd: server is-at <tcp/0.0.0.0:4004>
May 21 15:49:04 flexbuf4 ./Linux-x86_64-native-opt/etd[949]: 2021-05-21 13:49:04.20: server/TCP rcvbuf = 67108864 sndbuf = 67108864

**[flexbuf4 (socket-options)]Okay->pkill etd**

**[flexbuf4 (socket-options)]Okay->sudo grep etd /var/log/syslog**
_<< snip startup output as above >>_
May 21 15:49:28 flexbuf4 ./Linux-x86_64-native-opt/etd[949]: 2021-05-21 13:49:28.19: sigwaiterthread: got signal 15
May 21 15:49:28 flexbuf4 ./Linux-x86_64-native-opt/etd[949]: 2021-05-21 13:49:28.19: main: terminating because of signal#15
May 21 15:49:28 flexbuf4 ./Linux-x86_64-native-opt/etd[949]: 2021-05-21 13:49:28.19: Cancellation fn/signalling thread for data fd=674907568
May 21 15:49:28 flexbuf4 ./Linux-x86_64-native-opt/etd[949]: 2021-05-21 13:49:28.19: Cancellation fn/signalling thread for command fd=5
May 21 15:49:28 flexbuf4 ./Linux-x86_64-native-opt/etd[949]: 2021-05-21 13:49:28.19: main: terminating.
May 21 15:49:28 flexbuf4 ./Linux-x86_64-native-opt/etd[949]: 2021-05-21 13:49:28.19: ~etd_state/need to wait for 2 threads
May 21 15:49:28 flexbuf4 ./Linux-x86_64-native-opt/etd[949]: 2021-05-21 13:49:28.19: data server thread got exception: system call failed: /mnt/disk0/verkouter/etransfer/src/etdc_fd.h:768 failed to accept on udt[0.0.0.0:8008] - Operation not supported: Socket is not in listening state.
May 21 15:49:28 flexbuf4 ./Linux-x86_64-native-opt/etd[949]: 2021-05-21 13:49:28.19: data server thread terminated
May 21 15:49:28 flexbuf4 ./Linux-x86_64-native-opt/etd[949]: 2021-05-21 13:49:28.19: command server thread got exception: system call failed: /mnt/disk0/verkouter/etransfer/src/etdc_fd.h:660 failed to accept on tcp[0.0.0.0:4004] - Interrupted system call
May 21 15:49:28 flexbuf4 ./Linux-x86_64-native-opt/etd[949]: 2021-05-21 13:49:28.19: command server thread terminated

**Comment by varenius** [comment]
Ah! The difference is, you start etd with "-m 4". I started without any "-m" value. If I do that, there is nothing in the logfile.

Hmmm. I understand the approach of logging what you specify. It is very sensible. On the other hand, I also like some basic logging as default. Hm. Not sure what is best!

**Comment by haavee** [comment]
Well, with `m > 0` (or possibly with `m > 1`) the deamon already becomes pretty chatty.
Decision what you want spammed in your log is up to you. Of course message levels of certain events can easily be changed (made more important or less important); what is currently implemented is, after all, only a first approximation of what the (relative) importance of the info might be ...

**Comment by varenius** [comment]
Yes. I think we could close this ticket, as it is a matter of choice - and I cannot even agree with myself what I think would be the best one :).

**Comment by haavee** [comment]
I wonder who will win that argument :-) Good luck with that one!
